REG0										= $00	; 汎用0
REG1										= $01	; 汎用1
REG2										= $02	; 汎用2
REG3										= $03	; 汎用3
REG4										= $04	; 汎用4
REG5										= $05	; 汎用5
REG6										= $06	; 汎用6
scroll_x									= $07	; 
scroll_y									= $08	; 
player_draw_status							= $09	; 描画タイプ…0:通常、1:ジャンプ、2:攻撃中1、3:攻撃中2、4:死亡
attack_frame								= $0A	; 攻撃フレーム
count_y										= $0B
player_x_low								= $0C	; プレイヤ位置X（下位）上位はplayer_x_up
player_x_decimal							= $0D	; プレイヤ位置X（小数部）
player_y									= $0E	; プレイヤ位置Y（+1は小数部）
; 小数部									= $0F	
screen_x									= $10	; スクリーン位置
spd_y										= $11	; Y方向速度（+1は小数部）
; 小数部									= $12
spd_vec										= $13	; 速度方向（0下方向、1上方向）
player_spd_decial							= $14
player_spd_low								= $15
player_speed_hi_or_low						= $16	; プレイヤースピード速い
is_jump										= $17
p_pat										= $18	; プレイヤ描画パターン
pat_change_frame							= $19
chr_lr										= $1A	; キャラクタ左右フラグ
FIELD_HEIGHT								= $1B	; 地面の高さ
multiplicand								= $1C	; 被乗数（かけられる数）
multiplier									= $1D	; 乗数（かける数）
multi_ans_up								= $1E	; 乗算結果　上位ビット
multi_ans_low								= $1F	; 乗算結果　下位ビット
multi_loop_cnt								= $20	; 乗算用ループカウンタ
conv_coord_bit_x							= $21	; X座標
conv_coord_bit_y							= $22	; Y座標
conv_coord_bit_up							= $23	; 上位ビット
conv_coord_bit_low							= $24	; 下位ビット
draw_bg_tile								= $25	; タイル番号
draw_bg_x									= $26	; X座標
draw_bg_y									= $27	; Y座標
draw_bg_w									= $28	; 横ブロック数
draw_bg_h									= $29	; 縦ブロック数
draw_loop_x									= $2A	; ループ変数
draw_loop_y									= $2B	; ループ変数
bg_already_draw								= $2C	; BG描画済み変数（ブロック単位）
field_scroll_x_up							= $2D	; ゲーム内のスクロール位置上位
field_scroll_x_low							= $2E	; ゲーム内のスクロール位置下位
player_x_up									= $2F	; プレイヤ位置X上位
window_player_x_up							= $30	; ウィンドウ内の位置上位
window_player_x_low							= $31	; ウィンドウ内の位置下位
window_player_x_low8						= $32	; ウィンドウ内の位置-8下位
map_chip_index_up							= $33	; マップチップインデックス上位
map_chip_index_low							= $34	; マップチップインデックス下位
map_chip_offset_cal16_up					= $35	; マップチップオフセット
map_chip_offset_cal16_low					= $36	; マップチップオフセット
map_chip_offset_cal8_up						= $37	; マップチップオフセット
map_chip_offset_cal8_low					= $38	; マップチップオフセット
map_chip_offset_cal2_up						= $39	; マップチップオフセット
map_chip_offset_cal2_low					= $3A	; マップチップオフセット
map_chip_offset_cal_up						= $3B	; マップチップオフセット
map_chip_offset_cal_low						= $3C	; マップチップオフセット
map_chip_offset_up							= $3D	; マップチップオフセット
map_chip_offset_low							= $3E	; マップチップオフセット
map_chip_offset_start						= $3F	; マップチップオフセット
draw_bg_display								= $40	; 画面１画面２（20か24か）
draw_index_y								= $41	; 描画時のインデックスレジストリのテンプ
loop_count									= $42	; ループカウント
vblank_count								= $43	; VBlankのカウント
map_table_screen_low						= $44	; 
map_table_screen_hi							= $45	;
bg_already_draw_attribute					= $46	; BG属性設定済み変数（4ブロック単位）
map_table_attribute_low						= $47	; 
map_table_attribute_hi						= $48	;
offset_y_attribute							= $49	; 属性テーブルオフセットY
attribute_pos_adress_up						= $4A	; 属性テーブルの位置アドレス上位
attribute_pos_adress_low					= $4B	; 属性テーブルの位置アドレス下位
current_draw_display_no						= $4C	; 現在の描画画面番号（0 or 1）
map_table_now_low							= $4D	; 
map_table_now_hi							= $4E	;
bg_already_draw_pos							= $4F	; BG描画位置（ブロック単位）
bg_already_draw_attribute_pos				= $50	; BG属性設定位置（4ブロック単位）
pow_two										= $51
map_diff_x_index							= $52
map_chip_player_x_low						= $53	; あたり判定用キャラクタマップチップ座標X low
map_chip_player_x_hi						= $54	; あたり判定用キャラクタマップチップ座標X hi
map_chip_player_y							= $55	; あたり判定用キャラクタマップチップ座標Y
map_chip_collision_index_base_low			= $56
map_chip_collision_index_base_hi			= $57
map_table_char_pos_offset_low				= $58	; 
map_table_char_pos_offset_hi				= $59	;
map_table_char_pos_value					= $5A	;
obj_collision_result						= $5B	; オブジェクトとのあたり判定結果
player_y_top_for_collision					= $5C	;	あたり判定用上Y座標（Y座標）
player_y_bottom_for_collision				= $5D	;	あたり判定用下Y座標（Y座標+31）
player_x_left_hi_for_collision				= $5E	;	あたり判定用左X座標上位（X座標）
player_x_left_low_for_collision				= $5F	;	あたり判定用左X座標下位（X座標）
player_x_right_hi_for_collision				= $60	;	あたり判定用右X座標上位（X座標+15）
player_x_right_low_for_collision			= $61	;	あたり判定用右X座標下位（X座標+15）
map_chip_collision_index_left_bottom_low	= $62
map_chip_collision_index_left_bottom_hi		= $63
map_chip_collision_index_left_top_low		= $64
map_chip_collision_index_left_top_hi		= $65
map_chip_collision_index_right_bottom_low	= $66
map_chip_collision_index_right_bottom_hi	= $67
map_chip_collision_index_right_top_low		= $68
map_chip_collision_index_right_top_hi		= $69
obj_collision_pos							= $6A	; オブジェクトとの当たった場所(上下)(0～1)左下、左上、右下、右上
char_collision_result						= $6B	; 敵キャラとのあたり判定結果
is_dead										= $6C	; 死亡中
key_state_on								= $6D	; 現在のキーボード状態
key_state_on_old							= $6E	; 古いキーボード状態
key_state_push								= $6F	; このフレームで押された状態
update_dead_step							= $70	; 死亡時更新ステップ
wait_frame									= $71	; 待つフレーム
test_address_low							= $72
test_address_hi								= $73
scene_type									= $74	; シーン（0:TITLE 1:メイン 2:ゲームオーバー）
scene_update_step							= $75	; シーン用の更新ステップ
map_enemy_info_address_low					= $76
map_enemy_info_address_hi					= $77
enemy_kind									= $78	; 敵の種類
enemy_pos_x_low								= $79
enemy_pos_x_hi								= $7A
enemy_pos_y									= $7B
enemy_type									= $7C
inosisi_alive_flag							= $7D	; イノシシ生きているフラグ
inosisi_max_count							= $7E	; 最大同時数
inosisi_alive_flag_current					= $7F	; フラグ参照現在位置
inosisi0_world_pos_x_low					= $80	; イノシシ0 WORLD座標 X軸 下位
inosisi1_world_pos_x_low					= $81	; イノシシ1 WORLD座標 X軸 下位
inosisi0_world_pos_x_hi						= $82	; イノシシ0 WORLD座標 X軸 上位
inosisi1_world_pos_x_hi						= $83	; イノシシ1 WORLD座標 X軸 上位
inosisi0_pos_y								= $84	; イノシシ0 WORLD座標 Y軸
inosisi1_pos_y								= $85	; イノシシ1 WORLD座標 Y軸
inosisi0_window_pos_x						= $86	; イノシシ0 WINDOW座標 X軸
inosisi1_window_pos_x						= $87	; イノシシ1 WINDOW座標 X軸
obj_collision_sea							= $88	; 海と当たった判定
inosisi00_status							= $89	; イノシシ00状態(0:通常、1:溺れる、2:水しぶき1、3:水しぶき2)
inosisi01_status							= $8A	; イノシシ01状態(0:通常、1:溺れる、2:水しぶき1、3:水しぶき2)
inosisi00_wait								= $8B	; イノシシ00待ち
inosisi01_wait								= $8C	; イノシシ01待ち
inosisi00_update_dead_step					= $8D	; イノシシ00死亡時更新処理ステップ
inosisi01_update_dead_step					= $8E	; イノシシ01死亡時更新処理ステップ
scroll_count_8dot							= $8F	; スクロール用カウンタ
scroll_count_8dot_count						= $90	; スクロール用カウンタ
scroll_count_32dot							= $91	; スクロール用カウンタ
scroll_count_32dot_count					= $92	; スクロール用カウンタ
timer_bcd1									= $93	; タイマーBCD用2バイト目
timer_bcd0									= $94	; タイマーBCD用1バイト目
timer_b1									= $95	; タイマー2進数用2バイト目
timer_b0									= $96	; タイマー2進数用1バイト目
score_bcd2									= $97	; スコアBCD用3バイト目
score_bcd1									= $98	; スコアBCD用2バイト目
score_bcd0									= $99	; スコアBCD用1バイト目
score_b1									= $9A	; スコア2進数用2バイト目
score_b0									= $9B	; スコア2進数用1バイト目
count_up8									= $9C	; ループカウント
timer_count									= $9D	; タイマー用カウンタ
bgm_nomal_address_low						= $9E	;
bgm_nomal_address_hi						= $9F	;
bgm_nomal_sankaku_address_low				= $A0
bgm_nomal_sankaku_address_hi				= $A1
bgm_kukei_count								= $A2
bgm_sankaku_count							= $A3
bgm_kukei_step								= $A4
bgm_sankaku_step							= $A5
bgm_kukei_wait_frame						= $A6
bgm_sankaku_wait_frame						= $A7
bgm_type									= $A8
scene_maingame_init							= $A9
se_jump_address_low							= $AA	;
se_jump_address_hi							= $AB	;
se_type										= $AC
se_kukei_step								= $AD
se_kukei_count								= $AE
se_kukei_wait_frame							= $AF
tako_alive_flag								= $B0	; タコ生きているフラグ
tako_haba_alive_flag						= $B1	; はばタコ生きているフラグ
tako_max_count								= $B2	; 最大同時数
tako_alive_flag_current						= $B3	; フラグ参照現在位置
tako0_world_pos_x_decimal					= $B4	; タコ0 WORLD座標 X軸 小数部
tako1_world_pos_x_decimal					= $B5	; タコ1 WORLD座標 X軸 小数部
tako0_world_pos_x_low						= $B6	; タコ0 WORLD座標 X軸 下位
tako1_world_pos_x_low						= $B7	; タコ1 WORLD座標 X軸 下位
tako0_world_pos_x_hi						= $B8	; タコ0 WORLD座標 X軸 上位
tako1_world_pos_x_hi						= $B9	; タコ1 WORLD座標 X軸 上位
tako0_pos_y									= $BA	; タコ0 WORLD座標 Y軸
tako1_pos_y									= $BB	; タコ1 WORLD座標 Y軸
tako0_window_pos_x							= $BC	; タコ0 WINDOW座標 X軸
tako1_window_pos_x							= $BD	; タコ1 WINDOW座標 X軸
tako00_status								= $BE	; タコ00状態(0:通常、1:燃える)
tako01_status								= $BF	; タコ01状態(0:通常、1:燃える)
tamanegi_alive_flag							= $C0	; タマネギ生きているフラグ
tamanegi_max_count							= $C1	; 最大同時数
tamanegi_alive_flag_current					= $C2	; フラグ参照現在位置
tamanegi_type_flag							= $C3	; タマネギタイプ
tamanegi0_world_pos_x_decimal				= $C4	; タマネギ0 WORLD座標 X軸 小数部
tamanegi1_world_pos_x_decimal				= $C5	; タマネギ1 WORLD座標 X軸 小数部
tamanegi0_world_pos_x_low					= $C6	; タマネギ0 WORLD座標 X軸 下位
tamanegi1_world_pos_x_low					= $C7	; タマネギ1 WORLD座標 X軸 下位
tamanegi0_world_pos_x_hi					= $C8	; タマネギ0 WORLD座標 X軸 上位
tamanegi1_world_pos_x_hi					= $C9	; タマネギ1 WORLD座標 X軸 上位
tamanegi0_pos_y								= $CA	; タマネギ0 WORLD座標 Y軸
tamanegi1_pos_y								= $CB	; タマネギ1 WORLD座標 Y軸
tamanegi0_window_pos_x						= $CC	; タマネギ0 WINDOW座標 X軸
tamanegi1_window_pos_x						= $CD	; タマネギ1 WINDOW座標 X軸
tamanegi00_status							= $CE	; タマネギ00状態(0:大砲の中、1:放物線、2:通常、3:炎上)
tamanegi01_status							= $CF	; タマネギ01状態
tamanegi00_wait								= $D0	; タマネギ00待ち
tamanegi01_wait								= $D1	; タマネギ01待ち
tamanegi00_update_step						= $D2	; タマネギ00共通内部更新ステップ
tamanegi01_update_step						= $D3	; タマネギ01共通内部更新ステップ
tamanegi00_spd_y							= $D4	; Y方向速度（+1は小数部）
tamanegi01_spd_y							= $D5	; Y方向速度（+1は小数部）
tamanegi00_spd_y_decimal					= $D6	; 小数部
tamanegi01_spd_y_decimal					= $D7	; 小数部
tamanegi00_spd_vec							= $D8	; 速度方向（0下方向、1上方向）
tamanegi01_spd_vec							= $D9	; 速度方向（0下方向、1上方向）
cannon_world_x_low							= $DA
cannon_world_x_hi							= $DB
cannon_y									= $DC	;					(	0:なにもしない、1:2をタマネギ、2:3を炎
cannon_alive_flag							= $DD	;						3:4をはばタン、4:2をイノシシ、5:2をタコ
palette_change_state						= $DE	; パレットチェンジ用	6:3をタコ、7:3を酒下4を酒上、8:酒獲得			)
fire_alive_flag								= $DF	; 炎生きているフラグ
fire_max_count								= $E0	; 最大同時数
fire_alive_flag_current						= $E1	; フラグ参照現在位置
fire0_world_x_low							= $E2
fire1_world_x_low							= $E3
fire0_world_x_hi							= $E4
fire1_world_x_hi							= $E5
fire0_y										= $E6
fire1_y										= $E7
fire0_window_x								= $E8
fire1_window_x								= $E9
update_result								= $EA
habatan_alive_flag							= $EB	; はばタン生きているフラグ
habatan_world_pos_x_low						= $EC	; はばタン WORLD座標 X軸 下位
habatan_world_pos_x_hi						= $ED	; はばタン WORLD座標 X軸 上位
habatan_pos_y								= $EE	; はばタン WORLD座標 Y軸
habatan_window_pos_x						= $EF	; はばタン WINDOW座標 X軸
habatan_status								= $F0	; はばタン状態(0:近づく、1:くっつく、2:退場)
habatan_wait_low							= $F1	; はばタン登場フレーム
habatan_wait_hi								= $F2	; はばタン登場フレーム
habatan_fire_alive_flag						= $F3	; はばタンファイアー存在フラグ
habatan_fire_status							= $F4	; はばタンファイアー状態(0, 1, 2)
habatan_fire_wait							= $F5	; はばタンファイアー待ち
item_alive_flag								= $F6	; アイテム存在フラグ
item_world_pos_x_low						= $F7	; アイテムワールドX座標
item_world_pos_x_hi							= $F8	; アイテムワールドX座標
item_status									= $F9	; アイテム状態（0:表示、1:点滅）
item_window_pos_x							= $FA	; アイテムウィンドウX座標
item_pos_y									= $FB	; アイテムY座標
item_wait									= $FC	; アイテム待ち

debug_var									= $FF	; デバッグ用
